"""Artifacts CLI commands — retrieve artifacts by session or execution ID."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

if TYPE_CHECKING:
    from vlmrun.client import VLMRun

app = typer.Typer(
    help="Retrieve artifacts generated by chat completions or agent executions.",
    add_completion=False,
    no_args_is_help=True,
)

console = Console()


@app.command()
def list(
    ctx: typer.Context,
    session_id: str | None = typer.Option(
        None,
        "--session-id",
        "-s",
        help="Session ID to list artifacts for (mutually exclusive with --execution-id)",
    ),
    execution_id: str | None = typer.Option(
        None,
        "--execution-id",
        "-e",
        help="Execution ID to list artifacts for (mutually exclusive with --session-id)",
    ),
) -> None:
    """List artifacts for a session or execution."""
    client: VLMRun = ctx.obj

    if session_id is None and execution_id is None:
        console.print(
            "[red bold]Error:[/] Either --session-id or --execution-id is required."
        )
        raise typer.Exit(1)

    if session_id is not None and execution_id is not None:
        console.print(
            "[red bold]Error:[/] Only one of --session-id or --execution-id is allowed, not both."
        )
        raise typer.Exit(1)

    try:
        result = client.artifacts.list(
            session_id=session_id,
            execution_id=execution_id,
        )
    except Exception as exc:
        console.print(f"[red bold]Error:[/] {exc}")
        raise typer.Exit(1) from exc

    table = Table(title=f"Artifacts ({result.namespace_id})")
    table.add_column("Object ID", style="cyan")
    table.add_column("Filename")
    table.add_column("Source", style="green")

    for item in result.items:
        table.add_row(item.object_id, item.filename or "-", item.source)

    console.print(table)


@app.command()
def get(
    ctx: typer.Context,
    object_id: str = typer.Argument(
        ...,
        help="Object ID for the artifact (format: <type>_<6-hex-chars>, e.g. img_a1b2c3)",
    ),
    session_id: str | None = typer.Option(
        None,
        "--session-id",
        "-s",
        help="Session ID from chat completions (mutually exclusive with --execution-id)",
    ),
    execution_id: str | None = typer.Option(
        None,
        "--execution-id",
        "-e",
        help="Execution ID from agent executions (mutually exclusive with --session-id)",
    ),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Output file path. If omitted, the artifact is saved to the default cache directory.",
    ),
    raw: bool = typer.Option(
        False,
        "--raw",
        help="Return raw bytes instead of converting to the appropriate type.",
    ),
) -> None:
    """Download an artifact by object ID and session/execution ID."""
    client: VLMRun = ctx.obj

    if session_id is None and execution_id is None:
        console.print(
            "[red bold]Error:[/] Either --session-id or --execution-id is required."
        )
        raise typer.Exit(1)

    if session_id is not None and execution_id is not None:
        console.print(
            "[red bold]Error:[/] Only one of --session-id or --execution-id is allowed, not both."
        )
        raise typer.Exit(1)

    try:
        result = client.artifacts.get(
            object_id=object_id,
            session_id=session_id,
            execution_id=execution_id,
            raw_response=raw,
        )
    except Exception as exc:
        console.print(f"[red bold]Error:[/] {exc}")
        raise typer.Exit(1) from exc

    id_label = (
        f"session_id={session_id}" if session_id else f"execution_id={execution_id}"
    )

    if output is not None:
        _write_to_output(result, output)
        console.print(
            Panel(
                Text.from_markup(
                    f"[bold]Object ID:[/] {object_id}\n"
                    f"[bold]{id_label}[/]\n"
                    f"[bold]Saved to:[/]  [green]{output}[/]"
                ),
                title="[bold]Artifact Downloaded[/bold]",
                title_align="left",
                border_style="blue",
                padding=(0, 1),
            )
        )
        return

    # No explicit output — display what the SDK returned
    if isinstance(result, bytes):
        if output is None:
            console.print(
                f"[yellow]Received {len(result)} bytes. "
                "Use --output to save to a file.[/]"
            )
    elif isinstance(result, Path):
        console.print(
            Panel(
                Text.from_markup(
                    f"[bold]Object ID:[/] {object_id}\n"
                    f"[bold]{id_label}[/]\n"
                    f"[bold]Saved to:[/]  [green]{result}[/]"
                ),
                title="[bold]Artifact Downloaded[/bold]",
                title_align="left",
                border_style="blue",
                padding=(0, 1),
            )
        )
    else:
        # PIL Image or other types — save to cache and report
        try:
            from vlmrun.constants import VLMRUN_ARTIFACTS_CACHE_DIR

            sess_id: str = session_id or execution_id  # type: ignore[assignment]
            cache_dir = VLMRUN_ARTIFACTS_CACHE_DIR / sess_id
            cache_dir.mkdir(parents=True, exist_ok=True)
            dest = cache_dir / f"{object_id}.jpg"
            result.save(str(dest))
            console.print(
                Panel(
                    Text.from_markup(
                        f"[bold]Object ID:[/] {object_id}\n"
                        f"[bold]{id_label}[/]\n"
                        f"[bold]Saved to:[/]  [green]{dest}[/]"
                    ),
                    title="[bold]Artifact Downloaded[/bold]",
                    title_align="left",
                    border_style="blue",
                    padding=(0, 1),
                )
            )
        except Exception:
            console.print(f"[green]Artifact retrieved:[/] {type(result).__name__}")


def _write_to_output(result: object, output: Path) -> None:
    """Write an artifact result to the given output path.

    Args:
        result: The artifact content (bytes, Path, or PIL Image).
        output: Destination file path.
    """
    output.parent.mkdir(parents=True, exist_ok=True)

    if isinstance(result, bytes):
        output.write_bytes(result)
    elif isinstance(result, Path):
        import shutil

        shutil.copy2(result, output)
    else:
        # Assume PIL Image
        result.save(str(output))
