name: Main CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: dev
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    defaults:
      run:
        shell: bash -el {0}
    env:
      CACHE_NUMBER: 0

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('requirements/requirements*.txt') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('MANIFEST.in') }}-${{ env.CACHE_NUMBER }}
          restore-keys: |
            pip-${{ matrix.python-version }}-
        id: cache

      - name: Install base dependencies
        run: |
          which python
          python -m pip install --upgrade pip
          pip install -e '.[test,all]'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Quality Check
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      - name: Run all tests
        run: |
          # Install all extras and run complete test suite
          pip install -e '.[all]'
          pytest tests/common/test_dependencies.py -v
          make test
